stages:
  - lint
  - test

ruff_check:
  stage: lint
  image: python:3.14-slim
  tags:
    - public
  before_script:
    - python -m pip install --upgrade pip
    - pip install ruff
  script:
    - ruff format --isolated --check --config 'line-length = 120' --config 'format.quote-style = "double"' $(find . -type f -name '*.py' -not -path './.venv/*' -not -path './.git/*')
    - ruff check --isolated --config 'line-length = 120' --select E,F,W,B,I --ignore E402 $(find . -type f -name '*.py' -not -path './.venv/*' -not -path './.git/*')

moke_test:
  stage: test
  image: python:3.14-slim
  tags:
    - public
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
  script:
    - python .scripts/ci_moke_test.py
