[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trmoke_analysis"
version = "1.1.5"
description = "trMOKE analysis tools"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.11"
keywords = ["udkm", "MOKE", "data analysis"]
authors = [
  {name = "UDKM", email = "udkm-group@uni-potsdam.de"},
  {name = "Constantin Walz", email = "cwalz@uni-potsdam.de"}
]
maintainers = [
  {name = "Constantin Walz", email = "cwalz@uni-potsdam.de"}
]
dependencies = [
    "astropy>=7.2.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.9",
    "netCDF4>=1.7.4",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
    "xarray>=2026.4.0"
]
[tool.setuptools.packages.find]
where = ["."]
exclude = ["Examples*", "Remote*", ".scripts*", ".venv*"]
